 var book_array=[
 	{Img:'ScienceBook.jpg', Title:'The Science Book', Desc:'Science Book explores the history of science, how scientists have sought to explain our incredible universe and how amazing scientific discoveries have been made', Price:420000, Author:'Dorling Kindersley'},
 	{Img:'TheScienceBookEverythingYouNeedtoKnowAbouttheWorldandHowItWorks.jpg', Title:'The Science Book: Everything You Need to Know About the World and How It Works', Desc:'encapsulates centuries of scientific thought in one volume. Natural phenomena, revolutionary inventions, scientific facts, and the most up-to-date questions are all explained in detailed text that is complemented by visually arresting graphics', Price:350000, Author:'Marshall Brain'},
 	{Img:'ILoveScienceAJournalforSelfDiscoveryandBigIdeas.jpg', Title:'I Love Science: A Journal for Self-Discovery and Big Ideas', Desc:'Full of writing, drawing, and creativity prompts, I Love Science inspires kids (and adults) of all ages to fill the pages with ideas, self-exploration, and big dreams for the future', Price:150000, Author:'Rachel Ignotofsky'},
 	{Img:'NationalGeographicScienceofEverythingHowThingsWorkinOurWorld.jpg', Title:'National Geographic Science of Everything: How Things Work in Our World', Desc:'National Geographic answers all the questions about how things work--the science, technology, biology, chemistry, physics, and mechanics--in an indispensible book that reveals the science behind virtually everything', Price:320000, Author:'National Geographic'},
 	{Img:'ScienciaMathematicsPhysicsChemistryBiologyandAstronomyforAll.jpg', Title:'Sciencia: Mathematics, Physics, Chemistry, Biology, and Astronomy for All', Desc:'spanning the realms of mathematics, physics, chemistry, biology, evolution, and astronomy, offering invaluable information for readers. Lavishly illustrated with engravings, woodcuts, and original drawings and diagrams, Sciencia will inspire readers of all ages to take an interest in the interconnected knowledge of the modern science', Price:170000 ,Author:'Matt Tweed'},
 	{Img:'TheScienceofEverydayLifeWhyTeapotsDribbleToastBurnsandLightBulbsShine.JPG', Title:'The Science of Everyday Life : Why Teapots Dribble, Toast Burns and Light Bulbs Shine', Desc:'Have you ever wondered why ice floats and water is such a freaky liquid? Or why chillies and mustard are both hot but in different ways? Or why microwaves dont cook from the inside out? In this fascinating scientific tour of household objects', Price: 290000, Author:'Jopson, Marty'},
 	{Img:'WomeninScience50FearlessPioneersWhoChangedtheWorld.jpg', Title:'Women in Science: 50 Fearless Pioneers Who Changed the World', Desc:'A charmingly illustrated and educational book, New York Times best seller Women in Science highlights the contributions of fifty notable women to the fields of science, technology, engineering, and mathematics (STEM) from the ancient to the modern world', Price:110000,Author:'Rachel Ignotofsky'},
 	{Img:'WhatIfSeriousScientificAnswerstoAbsurdHypotheticalQuestions.jpg', Title:'What If?: Serious Scientific Answers to Absurd Hypothetical Questions', Desc:'The book features new and never-before-answered questions, along with updated and expanded versions of the most popular answers from the xkcd website. What If? will be required reading for xkcd fans and anyone who loves to ponder the hypothetical', Price:155000, Author:'Randall Munroe'},
 	{Img:'9.jpg',Title:'The Code Book: The Science of Secrecy from Ancient Egypt to Quantum Cryptography', Desc:'Simon Singh offers the first sweeping history of encryption, tracing its evolution and revealing the dramatic effects codes have had on wars, nations, and individual lives, The Code Book tells the story of the most powerful intellectual weapon ever known: secrecy',Price:250000, Author:'Simon Singh'},
 	{Img:'10.jpg', Title:'Cure: A Journey into the Science of Mind Over Body', Desc:'We learn how meditation protects against depression and dementia, how social connections increase life expectancy and how patients who feel cared for recover from surgery faster', Price: 152000, Author:'Jo Marchant'},
 	{Img:'11.jpg', Title:'Popular Science: The Big Book of Hacks: 264 Amazing DIY Tech Projects', Desc:'The ingenious and hilarious projects in The Big Book of Hacks are perfect for aspiring makers. And its all brought to you by the DIY masters at Popular Science magazine', Price: 60000, Author:'Doug Cantor'},
	{Img:'12.jpg', Title:'Algorithms to Live By: The Computer Science of Human Decisions', Desc:'how the algorithms used by computers can also untangle very human questions. They explain how to have better hunches and when to leave things to chance, how to deal with overwhelming choices and how best to connect with others. From finding a spouse to finding a parking spot, from organizing ones inbox to understanding the workings of memory', Price: 135000 , Author:'Brian Christian'},
 	{Img:'13.jpg', Title:'Everything You Need to Ace Science in One Big Fat Notebook', Desc:'takes readers from scientific investigation and the engineering design process to the Periodic Table; forces and motion; forms of energy; outer space and the solar system; to earth sciences, biology, body systems, ecology, and more', Price: 120000 , Author:'Workman Publishing'},
 	{Img:'14.jpg', Title:'Science Matters: Achieving Scientific Literacy', Desc:'Science Matters is a rare exception-a science book for the general reader that is informative enough to be a popular textbook for introductory courses in high school and college', Price:150000 , Author:'Robert M. hazen'},
 	{Img:'15.jpg', Title:'Superforecasting: The Art and Science of Prediction', Desc:'offer a masterwork on prediction, drawing on decades of research and the results of a massive, government-funded forecasting tournament', Price:156000 , Author:'Philip E. Tetlock'}
 
 ];

 $(document).ready(function(){
 	// for (book in book_array) {
 	// 	$('.book-content').append("<div class='box'><img src=assets/book_image/science/"+book_array[book]["Img"]+" width='100%' height='170px'><h3 id='titleId'>"+book_array[book]["Title"]+"</h3><p id='authorId'>"+book_array[book]["Author"]+"</p><p id='priceId'>Rp "+book_array[book]["Price"]+"</p><button id='showDescBtn'>Description</button></div>");
 	// 	// $('.popup-header').append("<h3>"+book_array[book]["Title"]+"</h3>");
 	// 	// $('.popup-body').append("<div>Description: "+book_array[book]["Desc"]+"</div><div><button id='addToCartBtn'>Add To Cart</button></div>");
 	// }
 });